version: 2
jobs:
  install-dependencies: &test
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm install --quiet
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
      - run: ./bin/run --version
      - run: ./bin/run --help
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: npm run ci tests
          command: npm run ci
      - run:
          name: coveralls test
          command: npm run test:cov && (cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js)
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run all scripts
          command: .circleci/scripts/run_all.sh
workflows:
  version: 2
  'project-starter':
    jobs:
      - install-dependencies
      - build:
          requires: [install-dependencies]
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
