version: 2
jobs:
  install-dependencies: &test
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm install --quiet
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
  test-and-lint:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run tests
          command: npm run ci
      - run:
          name: coveralls
          command: npm run test:cov && (cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js)
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run: sudo apt-get install p7zip-full
      - run:
          name: build binaries
          command: npm run oclif-pack
      - persist_to_workspace:
          root: ./
          paths: [dist]
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "84:43:03:4c:21:1e:e8:52:7e:69:67:fb:68:6f:81:9d"
      - attach_workspace:
          at: ./
      - run:
          name: deploy release on github
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_386.tar.gz
            tar -zxvf ghr_v0.12.0_linux_386.tar.gz 
            VERSION=$(bin/run --version | cut -d' ' -f 1 | cut -d'/' -f 3)
            echo ${VERSION}
            ghr_v0.12.0_linux_386/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/project-starter-cli-v${VERSION}/
      - run:
          name: git auth
          command: git config --global user.email "circleci@circleci.com" && git config --global user.name "circleci"
      - run:
          name: run scripts
          command: chmod +x .circleci/scripts/*.sh && .circleci/scripts/run_all.sh
  publish:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: publish release on npm registry
          command: npm run publish-npm
workflows:
  version: 2
  'project-starter':
    jobs:
      - install-dependencies
      - test-and-lint:
          requires: [install-dependencies]
      - build:
          requires: [install-dependencies, test-and-lint]
          filters:
            branches:
              only: master
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
      - publish:
          requires: [deploy]
          filters:
            branches:
              only: master
