---
version: 2
jobs:
  install-dependencies: &test
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run: ./bin/run --version
      - run: ./bin/run --help
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
        at: ./
      - run:
          name: npm run ci tests
          command: npm run ci

workflows:
  version: 2
  'project-starter':
    jobs:
      - node-latest
      - node-8
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
