version: 2
jobs:
  install-dependencies: &test
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm install --quiet
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
  test-and-lint:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run tests
          command: npm run ci
      - run:
          name: coveralls
          command: npm run test:cov && (cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js)
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run: sudo apt-get install p7zip-full
      - run:
          name: build binaries
          command: npm run oclif-pack
      - persist_to_workspace:
          root: ./
          paths: [dist]
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: deploy release on github
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_386.tar.gz
            tar -zxvf ghr_v0.12.0_linux_386.tar.gz
            VERSION=$(bin/run --version | cut -d' ' -f 1 | cut -d'/' -f 2)
            ghr_v0.12.0_linux_386/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/project-starter-cli-v${VERSION}/
  publish:
    docker:
      - image: circleci/node:8
      steps:
        - setup_remote_docker
        - checkout
        - attach_workspace:
            at: ./
        - run:
          name: publish release on npm registry
          command: npm run publish
workflows:
  version: 2
  'project-starter':
    jobs:
      - install-dependencies
      - test-and-lint:
          requires: [install-dependencies]
      - build:
          requires: [install-dependencies, test-and-lint]
          filters:
            branches:
              only: master
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
      - publish:
          requires: [deploy]
          filters:
            branches:
              only: master
